version: "3.8"

services:
  db:
    image: mongo:6.0.3
    command: --oplogSize 512 --replSet rs0 --bind_ip_all
    restart: unless-stopped
    expose:
      - 27017
    ports:
      - '27017:27017'
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' "localhost:27017/test" --quiet
      start_period: 40s
      retries: 3
      timeout: 7s
      interval: 10s
    networks:
      - accountEd-local
  db1:
    image: mongo:6.0.3
    command: --oplogSize 512 --replSet rs0 --bind_ip_all
    restart: unless-stopped
    expose:
      - 27017
    ports:
      - '27018:27017'
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' "localhost:27017/test" --quiet
      start_period: 40s
      retries: 3
      timeout: 7s
      interval: 10s
    networks:
      - accountEd-local
  db2:
    image: mongo:6.0.3
    command: --oplogSize 512 --replSet rs0 --bind_ip_all
    restart: unless-stopped
    expose:
      - 27017
    ports:
      - '27019:27017'
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' "localhost:27017/test" --quiet
      start_period: 40s
      retries: 3
      timeout: 7s
      interval: 10s
    networks:
      - accountEd-local
  mongo-init-replicas:
    image: mongo:6.0.3
    entrypoint: ["/scripts/setup.sh"]
    restart: 'no'
    depends_on:
      db:
        condition: service_healthy
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
    networks:
      - accountEd-local
    volumes:
      - ./scripts:/scripts
  mongo-migrate:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    image: mongo/migrator:6.0.3
    networks:
      - accountEd-local
    depends_on:
      mongo-init-replicas:
        condition: service_completed_successfully
    # volumes:
    #   - ./migrations/mongo/local/migration:/usr/local/migrate

#  app:
#    depends_on:
#      mongo-migrate:
#        condition: service_completed_successfully
#    image: accounted-${GOARCH:-amd64}-${ENV:-local}
#    networks:
#      - accountEd-local
#    ports:
#      - 8088:8088
#    command:
#      - /usr/ci-svc-usr/accountEd


networks:
  accountEd-local:
    driver: bridge
    attachable: true
