version: "3.8"

services:
  session:
    image: sch00l.io/session-${ENV}:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_PRE_REGISTRATION_PARAM=${AWS_PRE_REGISTRATION_PARAM}
      - AWS_REGION=${AWS_REGION}
      - AWS_ROLE_TO_ASSUME=${AWS_ROLE_TO_ASSUME}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SESSION_STORAGE_TABLE_NAME=${SESSION_STORAGE_TABLE_NAME}
    ports:
      - "${SESSION_PORT}:${SESSION_PORT}"