name: accountEd-backend

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "infrastructure/**"

  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.4'
          cache: true

      -
        run: |
          go version

      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Login to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        run: |
          make ci-buildx-register-image

      -
        run: |
          make build-binary

      -
        name: Copy Binary
        run: |
          mkdir artifacts
          cp accountEd artifacts/.

      -
        name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: accountEd
          path: artifacts
          retention-days: 7

      #  -
      #    name: Configure AWS credentials
      #    if: ${{ github.event_name != 'pull_request' }}
      #    uses: aws-actions/configure-aws-credentials@v1
      #    with:
      #      role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      #      aws-region: ${{ secrets.AWS_REGION }}
      #      role-duration-seconds: 900