name: accountEd-backend

on:
  push:
    branches:
      - main
      - develop
    paths:
      - backend/**
      - .github/workflows/application.yml
      - Makefile
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout
          uses: actions/checkout@v2.4.2
        -
          name: Cache Go Modules
          uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
        -
          name: Cache Docker Layers
          uses: actions/cache@v3
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-  
        -
          name: Configure AWS credentials
          if: ${{ github.event_name != 'pull_request' }}
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}
            role-duration-seconds: 900
        -
          name: Login to Amazon ECR
          if: github.event_name != 'pull_request'
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          with:
            registry-type: private
        -
          name: Login to GHCR
          if: ${{ github.event_name != 'pull_request' }}
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        -
          name: Build, tag, and push docker image to Amazon ECR
          if: github.event_name != 'pull_request'
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: sch00l.io-dev
            ENV: dev
            GH_ACTOR: ${{ github.actor }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            make ci-buildx-register-container
