name: members-build

on:
  push:
    branches:
      - '**'
    paths:
      - 'members/**'
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  build:
    name: members-build
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_PRE_REGISTRATION_HASH_PARAM: ${{ secrets.AWS_PRE_REGISTRATION_HASH_PARAM }}
      AWS_PRE_REGISTRATION_ROLE: ${{ secrets.AWS_PRE_REGISTRATION_ROLE }}
      DOMAIN: ${{ secrets.DOMAIN }}
      ENVIRONMENT: ${{ github.ref_name == 'alpha' && 'dev' || 'prod'}}
      GH_ACTOR: ${{ github.actor }}
      GH_REPOSITORY: 'codeclout/accounted'
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_TAG: ${{ github.sha }}
      MEMBER_PORT: ${{ secrets.MEMBER_PORT }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './members/go.mod'
          cache-dependency-path: './members/go.sum'
      -
        working-directory: './members'
        name: Vulnerabilities Check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
      -
        working-directory: './members'
        name: build-image
        run: |
          make build-image
      -
        name: scan-image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sch00l.io/members-${{env.ENVIRONMENT}}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
