name: build

on:
  push:
    branches:
      - '**'
    paths:
      - 'session/**'
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  build:
    name: session-build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_PRE_REGISTRATION_PARAM: ${{ secrets.AWS_PRE_REGISTRATION_PARAM }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV: ${{ github.ref_name == 'alpha' && 'dev' || 'prod'}}
      GH_ACTOR: ${{ github.actor }}
      GH_REPOSITORY: 'codeclout/accounted'
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_TAG: ${{ github.sha }}
      SESSION_PORT: ${{ secrets.SESSION_PORT }}
      SESSION_STORAGE_TABLE_NAME: ${{ secrets.SESSION_STORAGE_TABLE_NAME }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './session/go.mod'
          cache-dependency-path: './session/go.sum'
      -
        working-directory: './session'
        name: Vulnerabilities Check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
      -
        working-directory: './session'
        name: build-image
        run: |
          make build-image
      -
        name: scan-image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sch00l.io/session-${{env.ENV}}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
